export const GET_CURRENCY_RATES = 'api/GET_CURRENCY_RATES'
export const GET_CURRENCY_RATES_SUCCESS = 'api/GET_CURRENCY_RATES_SUCCESS'
export const GET_CURRENCY_RATES_ERROR = 'api/GET_CURRENCY_RATES_ERROR'
